from datetime import date

def get_ats_daily_report_email(
    total_apps: int,
    total_fields: int,
    total_autofill: int,
    total_llm: int,
    total_human: int,
    overall_auto_rate: float,
    table_rows: str
) -> str:
    """Daily ATS Application Report email — same style as professional_email_templates.py"""
    return f"""
    <html>
    <head>
        <meta charset="UTF-8">
        <style>
            body {{ font-family: Arial, sans-serif; background-color: #f9f9f9; color: #333; padding: 20px; margin: 0; }}
            .email-container {{ max-width: 960px; margin: 0 auto; background: #ffffff; padding: 30px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
            .header {{ background: linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%); color: #fff; text-align: center; padding: 25px; border-radius: 8px 8px 0 0; margin: -30px -30px 30px -30px; }}
            .header h1 {{ margin: 0; font-size: 24px; }}
            .header .subtitle {{ margin: 5px 0 0; font-size: 14px; opacity: 0.9; }}
            .summary-grid {{ display: flex; gap: 16px; flex-wrap: wrap; margin-bottom: 24px; }}
            .stat-box {{ flex: 1; min-width: 130px; background: #f1f3f4; border-radius: 8px; padding: 16px; text-align: center; }}
            .stat-box .value {{ font-size: 28px; font-weight: bold; color: #1a73e8; }}
            .stat-box .label {{ font-size: 12px; color: #666; margin-top: 4px; }}
            table {{ border-collapse: collapse; width: 100%; font-size: 14px; }}
            th {{ background-color: #1a73e8; color: #fff; padding: 10px 12px; text-align: left; }}
            td {{ padding: 9px 12px; border-bottom: 1px solid #e0e0e0; }}
            tr:nth-child(even) td {{ background-color: #f8f9fa; }}
            .footer {{ text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #eee; color: #777; font-size: 13px; }}
        </style>
    </head>
    <body>
        <div class="email-container">
            <div class="header">
                <h1>📊 Daily ATS Application Report</h1>
                <div class="subtitle">{date.today().strftime('%B %d, %Y')} — Automation Analytics</div>
            </div>

            <div class="summary-grid">
                <div class="stat-box"><div class="value">{total_apps}</div><div class="label">Total Applications</div></div>
                <div class="stat-box"><div class="value">{total_fields}</div><div class="label">Total Fields</div></div>
                <div class="stat-box"><div class="value">{total_autofill}</div><div class="label">Autofill Fields</div></div>
                <div class="stat-box"><div class="value">{total_llm}</div><div class="label">LLM Fields</div></div>
                <div class="stat-box"><div class="value">{total_human}</div><div class="label">Human Fields</div></div>
                <div class="stat-box"><div class="value">{overall_auto_rate}%</div><div class="label">Automation Rate</div></div>
            </div>

            <table>
                <tr>
                    <th>Candidate</th><th>Company</th><th>ATS Platform</th>
                    <th>Total Fields</th><th>Autofill</th><th>LLM</th><th>Human</th><th>Auto %</th>
                </tr>
                {table_rows}
            </table>

            <div class="footer">
                <p>This report was automatically generated by the WBox CLI ATS Automation System.</p>
                <p>Best regards,<br><strong>Innovapath Automation Team</strong></p>
            </div>
        </div>
    </body>
    </html>
    """
